export const ADD_IDEA = 'ADD_IDEA';
export const ADD_IDEA_SUCCESS = 'ADD_IDEA_SUCCESS';
export const ADD_IDEA_FAIL = 'ADD_IDEA_FAIL';

export const GET_IDEA_LIST = 'GET_IDEA_LIST';
export const GET_IDEA_LIST_SUCCESS = 'GET_IDEA_LIST_SUCCESS';
export const GET_IDEA_LIST_FAIL = 'GET_CATEGORY_LIST_FAIL';

export const GET_IDEAS_BY_TITLE = 'GET_IDEAS_BY_TITLE';
export const GET_IDEAS_BY_TITLE_SUCCESS = 'GET_IDEAS_BY_TITLE_SUCCESS';
export const GET_IDEAS_BY_TITLE_FAIL = 'GET_IDEAS_BY_TITLE_FAIL';
